import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FlipNav } from "@/components/nav-bar/NavBar";
import * as React from "react";
import menu from "../components/Menu/Menu";
// 1. import `HeroUIProvider` component
import { HeroUIProvider } from "@heroui/react";
import Header from "../components/header/index.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <HeroUIProvider>
        <body className={inter.className}>
          <div className="w-[100vw] z-[9999999] left-0 top-0 fixed">
            <div className="top-nav bg-[#5B6C2B] py-4 flex justify-center text-white">
              宜園建設：實在的構築
            </div>
            <Header />
            {/* <FlipNav /> */}
          </div>

          {children}
        </body>
        <footer className="h-[70vh] flex flex-col justify-center items-center bg-[#5b6c2b]">
          <div className="top w-[80%] mx-auto">
            <div className="w-1/2"></div>
            <div className="w-1/2"></div>
          </div>
          <div className="w-[80%] mx-auto bottom"></div>
        </footer>
      </HeroUIProvider>
    </html>
  );
}
